name: Deploy docs

on:
  push:
    branches: [main]
    paths:
      - 'docs/**'
      - 'demo/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn build
          echo ${{ secrets.CNAME }} > dist/CNAME
          chmod 600 dist/CNAME

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
