name: NPM Publish

on:
  push:
    tags:
      - "mcp-v*"
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          cache: yarn
      - run: yarn install --frozen-lockfile

      - name: Build
        run: |
          cp ./packages/vitepress-theme-async/types/theme.d.ts ./packages/mcp-server/bin
          node ./scripts/publish.mjs
          cd ./packages/mcp-server
          npm publish
        env:
          RELEASE_VERSION: ${{ github.ref }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}